spring.application.name=rooSemProblemas

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true

# Limite máximo para cada arquivo enviado
spring.servlet.multipart.max-file-size=10MB

# Limite máximo total da requisição (somando texto + imagem)
spring.servlet.multipart.max-request-size=10MB